library identifier: 'jenkins-sessions-library@main', 
retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/manudous/jenkins-sessions-library']) // [1]

pipeline {
  agent any

  stages {
    stage('Audit tools') {
      steps {
        auditTools()
      }
    }
  }
}